#!/bin/bash

# Check if PYFILE is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

# Compile the Python file
python -m py_compile "$PYFILE"

# Rename the output file to add 'c' at the end
mv "${PYFILE}c" "${PYFILE}c"
